site_name: MySQL Workbench User Guide

theme:
  name: material
  logo: assets/icons/logo.svg
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.top
    - search.highlight
    - content.tabs.link
    - content.code.copy
    

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - admonition
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
docs_dir: docs
copyright: >
  &copy; @mangoslush on Discord