site_name: MySQL Workbench User Guide
site_url: https://claisaz.github.io/mkdocs-MySQL-user-guide/
site_description: Beginner-friendly step-by-step guide to using MySQL Workbench on Windows.


nav:
  - Introduction: index.md
  - 1. Create a connection: 2-create-conn.md
  - 2. Create a schema: 3-createschema.md
  - 3. Create a table: 4-createtable.md
  - 4. Insert data: 5-insertdata.md
  - 5. Run your first query: 6-runquery.md
  - 6. View and edit data: 7-view-edit-data.md
  - Help:
      - Troubleshooting: troubleshooting.md
      - Glossary: zglossary.md

extra_css:
  - styles/theme-overrides.css

extra_javascript:
  - js/theme-default.js
  - js/troubleshooting.js

repo_url: https://github.com/ClaisaZ/mkdocs-MySQL-user-guide
repo_name: ClaisaZ/mkdocs-MySQL-user-guide
edit_uri: edit/main/docs/

theme:
  name: material
  logo: assets/icons/logo.svg
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye

  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.top
    - search.highlight
    - content.tabs.link
    - content.code.copy
    - navigation.footer
    - content.action.edit
    - content.action.view

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - admonition
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search
  - social:
      enabled: !ENV [CI, false]
  - git-revision-date-localized:
      type: date
  - glightbox

docs_dir: docs

copyright: >
  Copyright &copy; 2025 ClaisaZ & sawyer100

extra:
  generator: false
